@echo off
echo Starting Projet OASIS (Desktop Mode - No VR)...
"C:\Users\Utilisateur\AppData\Local\Microsoft\WinGet\Packages\GodotEngine.GodotEngine_Microsoft.Winget.Source_8wekyb3d8bbwe\Godot_v4.7.1-stable_win64.exe" --path "D:\xdev\Oasis"