# Genie Sim GLTF Runtime Importer (The Builder)
# Natively imports physical .gltf files generated by Genie Sim without freezing Godot.
class_name RuntimeAssetLoader
extends Node3D

signal gltf_loaded(node: Node3D)
signal load_failed(error: String)

func load_genie_sim_environment(file_path: String) -> void:
    print("[RuntimeAssetLoader] Importation de la generation Genie Sim: ", file_path)
    
    var gltf_doc = GLTFDocument.new()
    var gltf_state = GLTFState.new()
    
    # Note: L'importation runtime de gros fichiers peut créer un mini-lag.
    # Pour un projet VR, il est recommandé de l'exécuter dans un WorkerThreadPool.
    var error = gltf_doc.append_from_file(file_path, gltf_state)
    
    if error != OK:
        load_failed.emit("Erreur de lecture du fichier GLTF: " + str(error))
        return
        
    var generated_node = gltf_doc.generate_scene(gltf_state)
    if generated_node:
        add_child(generated_node)
        print("[RuntimeAssetLoader] Environnement GLTF integre a la scene avec succes!")
        gltf_loaded.emit(generated_node)
    else:
        load_failed.emit("Erreur lors de la generation de la scene 3D.")
