extends Node

# ==============================================================================
# PROJET OASIS - Runtime GLTF Asset Loader
# Dynamically loads .glb / .gltf assets generated by the ML Foundry backend.
# ==============================================================================

func load_glb_asset(path: String) -> Node3D:
	if not FileAccess.file_exists(path):
		print("[GLTF LOADER] File not found: ", path)
		return null
		
	var gltf_doc = GLTFDocument.new()
	var gltf_state = GLTFState.new()
	
	var err = gltf_doc.append_from_file(path, gltf_state)
	if err != OK:
		print("[GLTF LOADER] Error appending GLTF file: ", err)
		return null
		
	var node = gltf_doc.generate_scene(gltf_state)
	print("[GLTF LOADER] Successfully instantiated GLTF scene from: ", path)
	return node